### ISSUE TITLE
How can I change the source code and apply to my Mendix file (mpk)?

### ISSUE THREAD

**Issue by gucheolKwon** [e-mergo/mx-emergo-form-field-info-tooltip#1]
sincerely appreciate your widget. 
it can help user to use tooltip in dataview or data grid.

but I want to change the background color, text color and text box width. 
so how can I change them and apply to my mendix file?

**Comment by lmoffereins** [comment]
Hi @gucheolKwon, happy to hear the widget is of value to you.

The styling of all elements of the widget can be changed by adding CSS rules to your app. You can do this in the theme styling of any module in your app or in a dedicated UI resources module. Under styling/web create a new SCSS file in which to add the custom CSS rules and import the file in the main.scss file ([see documentation](https://docs.mendix.com/howto/front-end/customize-styling-new/)).

The class names of the popup elements are documented in the repos README file.

Example of custom SCSS styling:

```scss
.form-field-info-tooltip {
    width: 200px;
    color: white;
    background-color: red;

    .tooltip-popup-arrow {
        fill: red;
    }
}
```
